# Generated by Django 5.2.15 on 2026-06-30 03:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Email ini sudah terdaftar di sistem.'}, max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Format nomor telepon: '+628123456789'. Maks 15 digit.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Nomor Telepon')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Laki-laki'), ('F', 'Perempuan'), ('O', 'Lainnya')], max_length=1, verbose_name='Jenis Kelamin')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto Profil')),
                ('is_patient', models.BooleanField(default=True, verbose_name='Pasien')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='Dokter')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Apakah Two-Factor Authentication aktif', verbose_name='2FA Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Alamat Lengkap')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Kota')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provinsi')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kode Pos')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nama Kontak Darurat')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telp Kontak Darurat')),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='Contoh: Ayah, Ibu, Saudara, Teman', max_length=50, verbose_name='Hubungan')),
                ('preferred_language', models.CharField(choices=[('id', 'Bahasa Indonesia'), ('en', 'English')], default='id', max_length=10, verbose_name='Bahasa Preferensi')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferensi Notifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profil User',
                'verbose_name_plural': 'Profil Users',
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
    ]
