# Generated by Django 5.2.15 on 2026-06-30 03:37

import apps.devices.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('apple_watch', 'Apple Watch'), ('garmin', 'Garmin'), ('fitbit', 'Fitbit'), ('mi_band', 'Mi Band'), ('samsung', 'Samsung Galaxy Watch'), ('xiaomi', 'Xiaomi'), ('other', 'Lainnya')], max_length=20, verbose_name='Tipe Device')),
                ('device_name', models.CharField(max_length=100, verbose_name='Nama Device')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Firmware')),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('pairing', 'Pairing'), ('error', 'Error')], default='disconnected', max_length=15, verbose_name='Status Koneksi')),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baterai (%)')),
                ('device_token', models.CharField(default=apps.devices.models.generate_device_token, help_text='Token untuk autentikasi device (API key)', max_length=64, unique=True, verbose_name='Device Token')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Sync Terakhir')),
                ('paired_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pairing')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'ordering': ['-paired_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=10, verbose_name='Status Sync')),
                ('records_synced', models.PositiveIntegerField(default=0, verbose_name='Records Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Sync')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='devices.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'device_sync_logs',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', '-paired_at'], name='devices_user_id_d28592_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='devices_device__f7aa79_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['connection_status'], name='devices_connect_653c79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'serial_number')},
        ),
        migrations.AddIndex(
            model_name='devicesynclog',
            index=models.Index(fields=['device', '-synced_at'], name='device_sync_device__56c010_idx'),
        ),
    ]
