# Generated by Django 5.2.15 on 2026-06-30 03:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10, verbose_name='Level Alert')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('source_type', models.CharField(choices=[('sensor', 'Sensor'), ('vital', 'Vital Sign'), ('system', 'System')], default='sensor', max_length=20, verbose_name='Tipe Source')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Source ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Selesai')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Trigger')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Health Alert',
                'verbose_name_plural': 'Health Alerts',
                'db_table': 'health_alerts',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['user', '-triggered_at'], name='health_aler_user_id_2cec3e_idx'), models.Index(fields=['is_read', '-triggered_at'], name='health_aler_is_read_6c3f29_idx'), models.Index(fields=['alert_level', '-triggered_at'], name='health_aler_alert_l_50d3ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('nh3', 'Amonia (NH3)'), ('temperature', 'Suhu'), ('humidity', 'Kelembapan'), ('air_quality', 'Kualitas Udara'), ('co2', 'CO2'), ('pm25', 'PM2.5')], max_length=20, verbose_name='Tipe Sensor')),
                ('value', models.FloatField(verbose_name='Nilai Pembacaan')),
                ('unit', models.CharField(default='ppm', max_length=20, verbose_name='Satuan')),
                ('location', models.CharField(blank=True, help_text='Contoh: Ruang Tidur, Dapur, Kantor', max_length=100, verbose_name='Lokasi')),
                ('is_alert', models.BooleanField(default=False, help_text='Apakah pembacaan ini melebihi threshold', verbose_name='Status Alert')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Waktu Pembacaan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='devices.device', verbose_name='Device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Pembacaan Sensor',
                'verbose_name_plural': 'Pembacaan Sensor',
                'db_table': 'sensor_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sensor_type', '-recorded_at'], name='sensor_read_sensor__a3d07a_idx'), models.Index(fields=['user', '-recorded_at'], name='sensor_read_user_id_f8cc91_idx'), models.Index(fields=['is_alert', '-recorded_at'], name='sensor_read_is_aler_5a796a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Detak Jantung (bpm)')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tekanan Darah Sistolik (mmHg)')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tekanan Darah Diastolik (mmHg)')),
                ('oxygen_saturation', models.FloatField(blank=True, null=True, verbose_name='Saturasi Oksigen (%)')),
                ('body_temperature', models.FloatField(blank=True, null=True, verbose_name='Suhu Tubuh (°C)')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Laju Pernapasan (/menit)')),
                ('blood_glucose', models.FloatField(blank=True, null=True, verbose_name='Gula Darah (mg/dL)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Berat Badan (kg)')),
                ('steps', models.PositiveIntegerField(blank=True, null=True, verbose_name='Langkah')),
                ('sleep_hours', models.FloatField(blank=True, null=True, verbose_name='Durasi Tidur (jam)')),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kalori Terbakar')),
                ('is_anomaly', models.BooleanField(default=False, help_text='Apakah ada nilai yang tidak normal', verbose_name='Anomali')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Waktu Record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='devices.device', verbose_name='Source Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Vital Sign',
                'verbose_name_plural': 'Vital Signs',
                'db_table': 'vital_signs',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='vital_signs_user_id_aede43_idx'), models.Index(fields=['is_anomaly', '-recorded_at'], name='vital_signs_is_anom_b5c4d1_idx')],
            },
        ),
    ]
